openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: 認証サービスのAPI定義
servers:
  - url: http://localhost:8080
    description: ローカル開発環境
paths:
  /auth-service/api/auth/verify:
    post:
      summary: JWTトークンを検証
      description: JWTトークンを検証し、ユーザーIDを返却します。
      security:
        - bearerAuth: []
      responses:
        '200':
          description: トークンが有効
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: true
                  userId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                    description: JWTペイロードから抽出されたユーザーID（UUID形式）
                  expiresAt:
                    type: string
                    format: date-time
                    example: "2025-11-22T10:00:00Z"
        '401':
          description: 認証エラー（トークンが無効または期限切れ）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWTトークンによる認証。
        ペイロードには以下のクレームが必須:
        - userId: ユーザーID（UUID形式）
        - exp: 有効期限（Unix timestamp）
        - iat: 発行日時（Unix timestamp）
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid token"
        code:
          type: string
          example: "AUTH_ERROR"
        timestamp:
          type: string
          format: date-time
          example: "2025-11-21T10:00:00Z"
