openapi: 3.0.0
info:
  title: Point Service API
  version: 1.0.0
  description: ポイント管理サービスのAPI定義
servers:
  - url: http://localhost:8080
    description: ローカル開発環境
paths:
  /points/{userId}:
    get:
      summary: ユーザーのポイント残高を取得
      description: 指定されたユーザーIDのポイント残高を取得します。JWTトークンからユーザーIDを抽出して使用します。
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ユーザーID（UUID形式）
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                  balance:
                    type: integer
                    example: 1500
                    description: ポイント残高（pt）
                  updatedAt:
                    type: string
                    format: date-time
                    example: "2025-11-20T15:00:00Z"
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /points/history/{userId}:
    get:
      summary: ユーザーのポイント履歴を取得
      description: 指定されたユーザーIDのポイント履歴を取得します。
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ユーザーID（UUID形式）
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        operation:
                          type: string
                          enum: [取得, 使用, 失効]
                          example: "取得"
                        points:
                          type: integer
                          example: 200
                          description: 操作ポイント数（正の整数のみ）
                        expiresAt:
                          type: string
                          format: date-time
                          example: "2026-05-01T10:00:00Z"
                          nullable: true
                        createdAt:
                          type: string
                          format: date-time
                          example: "2025-11-01T10:00:00Z"
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /points/register:
    post:
      summary: ポイントを登録（内部向けAPI）
      description: 他サービスからポイントを登録します。
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - points
                - expiresAt
              properties:
                userId:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174001"
                points:
                  type: integer
                  example: 500
                  description: 付与ポイント数（正の整数）
                expiresAt:
                  type: string
                  format: date-time
                  example: "2026-05-21T10:00:00Z"
                  description: 失効予定日時
      responses:
        '201':
          description: 登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ポイントが正常に登録されました"
                  userId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                  points:
                    type: integer
                    example: 500
        '400':
          description: リクエストエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /points/use:
    post:
      summary: ポイントを使用（内部向けAPI）
      description: 他サービスからポイントを使用します。UI画面からの利用は不要。
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - points
              properties:
                userId:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174001"
                points:
                  type: integer
                  example: 100
                  description: 使用ポイント数（正の整数）
      responses:
        '200':
          description: 使用成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ポイントが正常に使用されました"
                  userId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                  usedPoints:
                    type: integer
                    example: 100
                  remainingBalance:
                    type: integer
                    example: 1400
        '400':
          description: リクエストエラー（残高不足など）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWTトークンによる認証。ペイロードには userId クレーム（UUID形式）が必須。
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "エラーメッセージ"
        code:
          type: string
          example: "ERROR_CODE"
        timestamp:
          type: string
          format: date-time
          example: "2025-11-21T10:00:00Z"
