openapi: 3.0.0
info:
  title: Point Service API
  version: 1.0.0
paths:
  /points/{userId}:
    get:
      summary: Get user points
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /points/history/{userId}:
    get:
      summary: Get user point history
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response