openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: ユーザーサービスのAPI定義
servers:
  - url: http://localhost:8080
    description: ローカル開発環境
paths:
  /user-service/api/users/{id}:
    get:
      summary: ユーザー情報を取得
      description: 指定されたIDのユーザー情報を取得します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ユーザーID（UUID形式）
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174001"
                  name:
                    type: string
                    example: "山田太郎"
                  email:
                    type: string
                    format: email
                    example: "yamada@example.com"
                  createdAt:
                    type: string
                    format: date-time
                    example: "2025-01-01T00:00:00Z"
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWTトークンによる認証。
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "エラーメッセージ"
        code:
          type: string
          example: "ERROR_CODE"
        timestamp:
          type: string
          format: date-time
          example: "2025-11-21T10:00:00Z"
